[package]
name = "pain_app"
version = "0.1.0"
edition = "2021"

[dependencies]
pain_core = { path = "../pain_core" }
pain_graphics = { path = "../pain_graphics" }
nalgebra = { workspace = true }
rand = { workspace = true }
sdl2 = { version = "0.36", features = ["ttf", "bundled"] }